### ISSUE TITLE
Há alguns problemas no Menu

### ISSUE THREAD

**Issue by SirBergue** [SirBergue/PokeZon#9]
a solução mais facil seria:
 - bloquear os movimentos, quando o menu estiver aberto
 - fechar o menu quando se movimentar

**Comment by KugiHaito** [comment]
**Bloquear os movimentos do Player, quando o menu estiver aberto** é mais apropriado, pois precisará ter um controle do menu, isto é, uma "setinha" apontando qual opção vai ser selecionada.
Para isto, será necessário ter o os botões: A, W, S, D e as "setinhas" do teclado disponíveis.

**Comment by SirBergue** [comment]
Sim boa solução, irei criar o sprite da setinha em src/letras

**Comment by SirBergue** [comment]
Resolvido.
